### PR TITLE
Add sherlock benchmark for regexes.

### PR DESCRIPTION
**Pull request by BurntSushi**

### CODE REVIEW

**Comment by MagaTailor** [comment]
I tried this benchmark out a few weeks ago - why so many individual results?

**Comment by BurntSushi** [comment]
I don't really understand the question. The performance of a regex engine is complex and varies with many factors.

**Comment by MagaTailor** [comment]
I may be misrembembering the original intention of this suite but I was probably expecting a more aggregate result in individual workload categories.

**Comment by BurntSushi** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
@BurntSushi ah, nice :) I missed this

**Pull request merged**
